# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170127_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ManyToManyField(blank=True, to='contacts.Business'),
        ),
    ]
