# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170131_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.ManyToManyField(to='contacts.Note'),
        ),
    ]
