# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20170131_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touch',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='touches',
            field=models.ManyToManyField(to='contacts.Touch'),
        ),
        migrations.AddField(
            model_name='touch',
            name='follow_up_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
