# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170131_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ManyToManyField(blank=True, to='contacts.Company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='touches',
            field=models.ManyToManyField(blank=True, to='contacts.Touch'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='touch',
            name='detail',
            field=models.TextField(max_length=140),
        ),
    ]
