# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20170131_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Note'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='touches',
        ),
        migrations.AddField(
            model_name='contact',
            name='touches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Touch'),
        ),
    ]
