# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170131_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField(max_length=140)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Company')),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Note')),
            ],
            options={
                'verbose_name_plural': ['touches'],
            },
        ),
        migrations.AlterModelOptions(
            name='touch',
            options={'verbose_name_plural': ['touches']},
        ),
    ]
