# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20170212_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touch',
            name='detail',
        ),
    ]
