# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_remove_touch_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Contact'),
        ),
    ]
